language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  secure: Px5cPES8lWegIKUymKzsRsUEqia9lCzOqVvtZ8nw9YjDZoyqYMNryiSF4BeHNqC1nWh00E7nxg2Ws1Q2B3nLU2gIKRXF2HFMr3dzk3JXRPTrpBoB+yASquSl+/rDcr7LCKjkdaUQBqfg+8bj6EPGijtmDlpGAQ1s5jvRpxrjxI/gQUBu7/4EeSfSYvOuXuhhgTKgBdk3frQNeAh/zI6fyB3PCj0e4TRr7PowFbp9qAAEYC3TsSoe1NjW8wzPbR8S08YSXWXCGswufORdPtsXIZCYDZReLt2Kynhqs5qRMq+06/gHYxCa8qZcgwaZkWmuXoen952Af2LqosgeKJPNcmR9X5Kp7X1ufRWy+SdqumO7vMi7N/PAjuiqJHkh6Ci5HIZZUmGum/McujOPGc6i/lR0crqgVMrb83Yzuv9rlGZRUtkaqxnaFsxSP6AXwa7GpL/lBhig1rCO2819fXhqTBuvOrTaP3ccvoPUgsrN58O1+f01+bo3dFdehXSrRNcCNQqmF02fxtEJ+shSGBzsMhrpTfAYarYjYDJqRG9YgkUKyDy6C+Ds1XYYnUCiniCenAGLsZlXjyiBdb8V4Gh+G1dySUzu81G1pwoeNDo84LAHzcsUbs+ND4e9TfPeNvgvlQzXnt6wQdNLh5jUiqrOX6zdAq7YxOJuO072Vvws5P4=
